### POST Validación JWT Proveedor
POST http://localhost:3000/auth/
Content-Type: application/json

{
    "username": "ProveedorPerez",
    "password": "rperez24"
}

### POST Validación JWT Administrador
POST http://localhost:3000/auth/
Content-Type: application/json

{
    "username": "nrosales",
    "password": "nrosales90"
}

### POST Validación JWT Usuario
POST http://localhost:3000/auth/
Content-Type: application/json

{
    "username": "nusuario",
    "password": "nusuario90"
}

/////////////////////////////////////////////////////////////////////
### Users Controller

### GET Users
GET http://localhost:3000/usuarios/

### GET Users por ID
GET http://localhost:3000/usuarios/2

### PATCH Editar usuario
PATCH http://localhost:3000/usuarios/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsInVzZXJuYW1lIjoiUHJvdmVlZG9yUGVyZXoiLCJ1c2VyTGV2ZWwiOjIsImV4cCI6MTY5ODMzNjkyNzMxMSwiaWF0IjoxNjk4MzM2Njg3fQ.vrFnleCQYM_kOHdSBNhXYtfhdEFRiHRdw2kY1cNtjVg

{
    "email": "ppascalNuevo2@gmail.com"
}

### POST Users
POST http://localhost:3000/usuarios/
Content-Type: application/json

{
    "first_name": "Nuevo",
    "last_name": "Usuario",
    "username": "nusuario",
    "email": "nusuario@gmail.com",
    "password": "nusuario90",
    "id_user_cat": 1
}

### DELETE User
DELETE http://localhost:3000/usuarios/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsInVzZXJuYW1lIjoibnVzdWFyaW8iLCJ1c2VyTGV2ZWwiOjEsImV4cCI6MTY5ODYxNTQwNTUwMywiaWF0IjoxNjk4NjE1MTY1fQ.6A8HdGkMg63l65_NmQCjbTuhPdqpDDFtsTt-lRWUfpA

/////////////////////////////////////////////////////////////////////

### Products Controller

### GET Products
GET http://localhost:3000/productos/

### GET Product ID
GET http://localhost:3000/productos/1

### Agregado de un producto nuevo, el body lleva el json con el objeto
POST http://localhost:3000/productos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoibnJvc2FsZXMiLCJ1c2VyTGV2ZWwiOjMsImV4cCI6MTY5ODMzNjE4MDQzOSwiaWF0IjoxNjk4MzM1OTQwfQ.tUVhpOxwDZA_ygqmmIAJysFLR4Acc8xIJm4b7Qoe88w

{
    "id_product_cat": 1,
    "description": "Cable Ethernet 4mts Gris",
    "price_list": 150.50,
    "id_provider": 1,
    "price_public": 250.50,
    "stock": 10
}

### PATCH Product
PATCH http://localhost:3000/productos/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsInVzZXJuYW1lIjoiUHJvdmVlZG9yUGVyZXoiLCJ1c2VyTGV2ZWwiOjIsImV4cCI6MTY5ODYxNjE4NDkzNywiaWF0IjoxNjk4NjE1OTQ0fQ.O8Ci4cA8uSUzDneqe6jBvVOPeXAGKhNEWHQg88YCYKE

{
    "price_list": 180.50,
    "price_public": 280.50
}

### Eliminar Producto por ID, Validación Administrador
DELETE http://localhost:3000/productos/9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoibnJvc2FsZXMiLCJ1c2VyTGV2ZWwiOjMsImV4cCI6MTY5ODMzNjE4MDQzOSwiaWF0IjoxNjk4MzM1OTQwfQ.tUVhpOxwDZA_ygqmmIAJysFLR4Acc8xIJm4b7Qoe88w


/////////////////////////////////////////////////////////////////////

### Cart Controller

### Obtener lista de carritos
GET http://localhost:3000/carro/

### Obtener carrito por ID
GET http://localhost:3000/carro/6

### Post Nuevo Carrito // Requiere Usuario
POST http://localhost:3000/carro
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInVzZXJuYW1lIjoicHBhc2NhbCIsInVzZXJMZXZlbCI6MSwiZXhwIjoxNjk4MzQxNjA1NDkyLCJpYXQiOjE2OTgzNDEzNjV9.h4WF8xhP7zrWxdlyFOzL2j3m9d5sk7m7zs42OM29cso

{
    "id_user": 2
}


/////////////////////////////////////////////////////////////////////

### Cart Item Controller

### Get Items carrito
GET http://localhost:3000/item/

### Get Items carrito por ID
GET http://localhost:3000/item/1

### Post Nuevo Item de Carrito // Requiere Usuario
POST http://localhost:3000/item
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsInVzZXJuYW1lIjoibnVzdWFyaW8iLCJ1c2VyTGV2ZWwiOjEsImV4cCI6MTY5ODY5MTA1MTIwMiwiaWF0IjoxNjk4NjkwODExfQ.bKC0SdqRSugdqPUZGrEI612ZnshaLLjz5bJ--6NU-zU

{
    "id_product": 1,
    "qty": 4
}

### Editar Item de Carrito
PATCH http://localhost:3000/item/1
Content-Type: application/json

{
    "qty": 5
}

### Eliminar Item de Carrito
DELETE http://localhost:3000/item/4
Content-Type: application/json

/////////////////////////////////////////////////////////////////////

### Product Category Controller

### GET Product Categories
GET http://localhost:3000/categorias/

### GET Product Category por ID
GET http://localhost:3000/categorias/1

### POST Product Category // Requiere Proveedor
POST http://localhost:3000/categorias/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsInVzZXJuYW1lIjoiUHJvdmVlZG9yUGVyZXoiLCJ1c2VyTGV2ZWwiOjIsImV4cCI6MTY5ODc4ODc2NjU3NiwiaWF0IjoxNjk4Nzg4NTI2fQ.HLDsHXEalgIRZb4sz6Q-1fBqP0z2l6HkRFcmauqedEw

{
    "category": "Adaptadores HDMI",
    "description": "HDMI/VGA, HDMI HUBs, HDMI/Display"
}

### PATCH Product Category // Requiere Proveedor
PATCH http://localhost:3000/categorias/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsInVzZXJuYW1lIjoiUHJvdmVlZG9yUGVyZXoiLCJ1c2VyTGV2ZWwiOjIsImV4cCI6MTY5ODYxOTE5NDg4NSwiaWF0IjoxNjk4NjE4OTU0fQ.UoWWpzHNv6yekiWEs-K2mss_Kkr0TGukE3-HeqE2CmQ

{
    "category": "Cables/Extensiones"
}

### DELETE Product Category // Requiere Administrador
DELETE http://localhost:3000/categorias/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoibnJvc2FsZXMiLCJ1c2VyTGV2ZWwiOjMsImV4cCI6MTY5ODYxOTMwMzc4NSwiaWF0IjoxNjk4NjE5MDYzfQ.YEX4em0wRJbwBSJmy65w9AwFytlLPyJIaMaPfS1ReA4

/////////////////////////////////////////////////////////////////////

### Provider Controller

### GET Providers
GET http://localhost:3000/proveedores/

### GET Provider por ID
GET http://localhost:3000/proveedores/1

### POST Provider // Requiere Administrador
POST http://localhost:3000/proveedores
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoibnJvc2FsZXMiLCJ1c2VyTGV2ZWwiOjMsImV4cCI6MTY5ODYyMjg5Nzg0MywiaWF0IjoxNjk4NjIyNjU3fQ.XSLkNZXtILNH8HlEKUqUaMhjZli2xLvdpPIauSLKxto

{
    "id_user": 1,
    "cuit": 30374431208
}

### PATCH Provider // Requiere Administrador
PATCH http://localhost:3000/proveedores/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoibnJvc2FsZXMiLCJ1c2VyTGV2ZWwiOjMsImV4cCI6MTY5ODYyMzM2MzQzNywiaWF0IjoxNjk4NjIzMTIzfQ.W0vWiIw9JfIXk3KqtWQc02DDSykDkT5dF6tnpIP1LHo

{
    "id_user": 3
}

### DELETE Provider // Requiere Administrador
DELETE http://localhost:3000/proveedores/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoibnJvc2FsZXMiLCJ1c2VyTGV2ZWwiOjMsImV4cCI6MTY5ODYyMjg5Nzg0MywiaWF0IjoxNjk4NjIyNjU3fQ.XSLkNZXtILNH8HlEKUqUaMhjZli2xLvdpPIauSLKxto

/////////////////////////////////////////////////////////////////////

### Sales Controller

### GET Sales
GET http://localhost:3000/ventas

### GET Sale by ID
GET http://localhost:3000/ventas/3

### POST Sale // Requiere Usuario
POST http://localhost:3000/ventas
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInVzZXJuYW1lIjoicHBhc2NhbCIsInVzZXJMZXZlbCI6MSwiZXhwIjoxNjk4NjQzMzM2NTk3LCJpYXQiOjE2OTg2NDMwOTZ9.aUcbX5BQn5VFY74zC6rEsvSQ10dWpOB2lzz2vtx0jq4

{
    "id_cart": 1
}

### DELETE Sale // Requiere Administrador
DELETE http://localhost:3000/ventas/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoibnJvc2FsZXMiLCJ1c2VyTGV2ZWwiOjMsImV4cCI6MTY5ODY0MDAxNTc3MywiaWF0IjoxNjk4NjM5Nzc1fQ.i-LQ1LxL_t5tO8ReXcfMOfAvS4ApZCWaLESNbV0loww