### POST Validación JWT
POST http://localhost:3000/auth/
Content-Type: application/json

{
    "username": "ProveedorPerez",
    "password": "rperez24"
}

### POST Validación JWT
POST http://localhost:3000/auth/
Content-Type: application/json

{
    "username": "nrosales",
    "password": "nrosales90"
}

/////////////////////////////////////////////////////////////////////
### Users Controller

### GET Users
GET http://localhost:3000/usuarios/

### PATCH Editar usuario
PATCH http://localhost:3000/usuarios/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsInVzZXJuYW1lIjoiUHJvdmVlZG9yUGVyZXoiLCJ1c2VyTGV2ZWwiOjIsImV4cCI6MTY5ODMzNjkyNzMxMSwiaWF0IjoxNjk4MzM2Njg3fQ.vrFnleCQYM_kOHdSBNhXYtfhdEFRiHRdw2kY1cNtjVg

{
    "email": "ppascalNuevo2@gmail.com"
}

### POST Users
POST http://localhost:3000/usuarios/
Content-Type: application/json

{
    "first_name": "Nuevo",
    "last_name": "Usuario",
    "username": "nusuario",
    "email": "nusuario@gmail.com",
    "password": "nusuario90",
    "id_user_cat": 1
}

### DELETE User
DELETE http://localhost:3000/usuarios/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsInVzZXJuYW1lIjoibnVzdWFyaW8iLCJ1c2VyTGV2ZWwiOjEsImV4cCI6MTY5ODYxNTQwNTUwMywiaWF0IjoxNjk4NjE1MTY1fQ.6A8HdGkMg63l65_NmQCjbTuhPdqpDDFtsTt-lRWUfpA

/////////////////////////////////////////////////////////////////////

### Products Controller

### GET Products
GET http://localhost:3000/productos/

### GET Product ID
GET http://localhost:3000/productos/1

### Agregado de un producto nuevo, el body lleva el json con el objeto
POST http://localhost:3000/productos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoibnJvc2FsZXMiLCJ1c2VyTGV2ZWwiOjMsImV4cCI6MTY5ODMzNjE4MDQzOSwiaWF0IjoxNjk4MzM1OTQwfQ.tUVhpOxwDZA_ygqmmIAJysFLR4Acc8xIJm4b7Qoe88w

{
    "id_product_cat": 1,
    "description": "Cable Ethernet 4mts Gris",
    "price_list": 150.50,
    "id_provider": 1,
    "price_public": 250.50,
    "stock": 10
}

### PATCH Product
PATCH http://localhost:3000/productos/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsInVzZXJuYW1lIjoiUHJvdmVlZG9yUGVyZXoiLCJ1c2VyTGV2ZWwiOjIsImV4cCI6MTY5ODYxNjE4NDkzNywiaWF0IjoxNjk4NjE1OTQ0fQ.O8Ci4cA8uSUzDneqe6jBvVOPeXAGKhNEWHQg88YCYKE

{
    "price_list": 180.50,
    "price_public": 280.50
}

### Eliminar Producto por ID, Validación Administrador
DELETE http://localhost:3000/productos/9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoibnJvc2FsZXMiLCJ1c2VyTGV2ZWwiOjMsImV4cCI6MTY5ODMzNjE4MDQzOSwiaWF0IjoxNjk4MzM1OTQwfQ.tUVhpOxwDZA_ygqmmIAJysFLR4Acc8xIJm4b7Qoe88w


/////////////////////////////////////////////////////////////////////

### Cart Controller

### Obtener lista de carritos
GET http://localhost:3000/carro/

### Obtener carrito por ID
GET http://localhost:3000/carro/6

### Post Nuevo Carrito
POST http://localhost:3000/carro
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInVzZXJuYW1lIjoicHBhc2NhbCIsInVzZXJMZXZlbCI6MSwiZXhwIjoxNjk4MzQxNjA1NDkyLCJpYXQiOjE2OTgzNDEzNjV9.h4WF8xhP7zrWxdlyFOzL2j3m9d5sk7m7zs42OM29cso

{
    "id_user": 2
}


/////////////////////////////////////////////////////////////////////

### Cart Item Controller

### Get Items carrito
GET http://localhost:3000/item/

### Get Items carrito por ID
GET http://localhost:3000/item/1

### Post Nuevo Item de Carrito
POST http://localhost:3000/item
Content-Type: application/json

{
    "id_product": 2,
    "qty": 2,
    "id_cart": 6
}

### Editar Item de Carrito
PATCH http://localhost:3000/item/1
Content-Type: application/json

{
    "qty": 5
}

### Eliminar Item de Carrito
DELETE http://localhost:3000/item/2
Content-Type: application/json

/////////////////////////////////////////////////////////////////////

### Product Category Controller

### GET Product Categories
GET http://localhost:3000/categories/

### GET Product Category por ID
GET http://localhost:3000/categories/1

### POST Product Category
POST http://localhost:3000/categories/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsInVzZXJuYW1lIjoiUHJvdmVlZG9yUGVyZXoiLCJ1c2VyTGV2ZWwiOjIsImV4cCI6MTY5ODYxODg2MTU4MywiaWF0IjoxNjk4NjE4NjIxfQ.6UBEhKTGxbj2YG_UwhHr5qwBNHhbg10QCpKPJTiFkLQ

{
    "category": "Adaptadores HDMI",
    "description": "HDMI/VGA, HDMI HUBs, HDMI/Display"
}

### PATCH Product Category
PATCH http://localhost:3000/categories/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsInVzZXJuYW1lIjoiUHJvdmVlZG9yUGVyZXoiLCJ1c2VyTGV2ZWwiOjIsImV4cCI6MTY5ODYxOTE5NDg4NSwiaWF0IjoxNjk4NjE4OTU0fQ.UoWWpzHNv6yekiWEs-K2mss_Kkr0TGukE3-HeqE2CmQ

{
    "category": "Cables/Extensiones"
}

### DELETE Product Category
DELETE http://localhost:3000/categories/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoibnJvc2FsZXMiLCJ1c2VyTGV2ZWwiOjMsImV4cCI6MTY5ODYxOTMwMzc4NSwiaWF0IjoxNjk4NjE5MDYzfQ.YEX4em0wRJbwBSJmy65w9AwFytlLPyJIaMaPfS1ReA4

/////////////////////////////////////////////////////////////////////

### Provider Controller

### GET Providers
GET http://localhost:3000/proveedores/

### GET Provider por ID
GET http://localhost:3000/proveedores/1

### POST Provider
POST http://localhost:3000/proveedores
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoibnJvc2FsZXMiLCJ1c2VyTGV2ZWwiOjMsImV4cCI6MTY5ODYyMjg5Nzg0MywiaWF0IjoxNjk4NjIyNjU3fQ.XSLkNZXtILNH8HlEKUqUaMhjZli2xLvdpPIauSLKxto

{
    "id_user": 1,
    "cuit": 30374431208
}

### PATCH Provider
PATCH http://localhost:3000/proveedores/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoibnJvc2FsZXMiLCJ1c2VyTGV2ZWwiOjMsImV4cCI6MTY5ODYyMzM2MzQzNywiaWF0IjoxNjk4NjIzMTIzfQ.W0vWiIw9JfIXk3KqtWQc02DDSykDkT5dF6tnpIP1LHo

{
    "id_user": 3
}

### DELETE Provider
DELETE http://localhost:3000/proveedores/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoibnJvc2FsZXMiLCJ1c2VyTGV2ZWwiOjMsImV4cCI6MTY5ODYyMjg5Nzg0MywiaWF0IjoxNjk4NjIyNjU3fQ.XSLkNZXtILNH8HlEKUqUaMhjZli2xLvdpPIauSLKxto