### Obtener lista de usuarios
GET http://localhost:3000/usuarios/

### Obtener lista de productos
GET http://localhost:3000/productos/

### POST Validación JWT
POST http://localhost:3000/auth/
Content-Type: application/json

{
    "username": "ppascal",
    "password": "ppascal18"
}

### Post Nuevo Carrito
POST http://localhost:3000/carro
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInVzZXJuYW1lIjoicHBhc2NhbCIsInVzZXJMZXZlbCI6MSwiZXhwIjoxNjk4MzQxNjA1NDkyLCJpYXQiOjE2OTgzNDEzNjV9.h4WF8xhP7zrWxdlyFOzL2j3m9d5sk7m7zs42OM29cso

{
    "id_user": 2
}


### Patch Editar usuario
PATCH http://localhost:3000/usuarios/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsInVzZXJuYW1lIjoiUHJvdmVlZG9yUGVyZXoiLCJ1c2VyTGV2ZWwiOjIsImV4cCI6MTY5ODMzNjkyNzMxMSwiaWF0IjoxNjk4MzM2Njg3fQ.vrFnleCQYM_kOHdSBNhXYtfhdEFRiHRdw2kY1cNtjVg

{
    "email": "ppascalNuevo2@gmail.com"
}

### Agregado de un producto nuevo, el body lleva el json con el objeto
POST http://localhost:3000/productos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoibnJvc2FsZXMiLCJ1c2VyTGV2ZWwiOjMsImV4cCI6MTY5ODMzNjE4MDQzOSwiaWF0IjoxNjk4MzM1OTQwfQ.tUVhpOxwDZA_ygqmmIAJysFLR4Acc8xIJm4b7Qoe88w


{
    "id_product_cat": 1,
    "description": "Cable Ethernet 4mts Gris",
    "price_list": 150.50,
    "id_provider": 1,
    "price_public": 250.50,
    "stock": 10
}

### Eliminar Producto por ID, Validación Administrador
DELETE http://localhost:3000/productos/9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoibnJvc2FsZXMiLCJ1c2VyTGV2ZWwiOjMsImV4cCI6MTY5ODMzNjE4MDQzOSwiaWF0IjoxNjk4MzM1OTQwfQ.tUVhpOxwDZA_ygqmmIAJysFLR4Acc8xIJm4b7Qoe88w